version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - pip install -r requirements.txt

  pre_build:
    on-failure: ABORT
    commands:
      - aws s3 cp s3://jtamu-chalice-deployed-bucket01/google_login_back/dev.json .chalice/deployed/dev.json || true
      - ./test.sh

  build:
    on-failure: ABORT
    commands:
      - chalice deploy

  post_build:
    on-failure: ABORT
    commands:
      - aws s3 cp .chalice/deployed/dev.json s3://jtamu-chalice-deployed-bucket01/google_login_back/dev.json
      - python create_table.py
