version: '3'
services:
  python:
    build:
      context: .
    volumes:
      - .:/work
      - ~/.aws/:/root/.aws
    ports:
      - 8002:8002
    environment:
      DB_ENDPOINT: http://dynamo:8000
      TEST_PORT: 8008
      PACT_BROKER_BASE_URL: ${PACT_BROKER_BASE_URL}
      PACT_BROKER_AUTH: ${PACT_BROKER_USERNAME}:${PACT_BROKER_PASSWORD}
    command: chalice local --host=0.0.0.0 --port=8002
  dynamo:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - ./dynamodb:/home/dynamodblocal/data
  dynamo-test:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - ./dynamodb-test:/home/dynamodblocal/data

  dynamo-admin:
    image: aaronshaf/dynamodb-admin:latest
    environment:
      DYNAMO_ENDPOINT: dynamo:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamo
