version: '3'
services:
  python:
    build:
      context: .
    volumes:
      - .:/work
    ports:
      - 8002:8002
    environment:
      DB_ENDPOINT: http://dynamo:8000
      TEST_PORT: 8008
      PACT_BROKER_BASE_URL: ${PACT_BROKER_BASE_URL}
      PACT_BROKER_AUTH: ${PACT_BROKER_USERNAME}:${PACT_BROKER_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_DEFAULT_REGION: ap-northeast-1
    command: chalice local --host=0.0.0.0 --port=8002
  dynamo:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - ./dynamodb:/home/dynamodblocal/data
  dynamo-test:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - ./dynamodb-test:/home/dynamodblocal/data
    ports:
      - 8003:8000

  dynamo-admin:
    image: aaronshaf/dynamodb-admin:latest
    environment:
      DYNAMO_ENDPOINT: dynamo:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamo
